application: locationfindercs4720
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: locationfinder.application


libraries:
- name: webapp2
  version: "latest"

builtins:
- remote_api: on



